##### INDEX PAGE ####

title = "The Triumvirate of Agency"
subtitle = '''
There is nothing new in this book

Author: Tristram Oaten <o@tman.me>
'''
baseurl = ""

#### PATHS ####

# These paths should be relative to to where you run
# markdown2tufte

# Path to all images
images = "images"

# Path to all markdown
files = "chapters"

#### POSTS ####

# Posts will appear in the order they are
# set here
# 'slug' is an optional parameter (defaults to filename)

[[post]]
filename = "README.md"
title = "Getting started"
subtitle = "Read me first."

